#!/usr/bin/env bash
#
# Confirm
read -p "Are you sure(y/n)? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
fi

# Actual code
command="$@"
sites=($(drush -n @sites 2> /dev/null | grep "  /"))
for i in "${sites[@]}"
do
  uri=$(cut -d "#" -f 2 <<< "$i")
  finalcommand="drush -y --uri=$uri $command"
  add_drush="&& drush -y --uri=$uri"
  finalcommand="${finalcommand//&&/$add_drush}"
  echo "======= SITE: $uri. COMMAND: $finalcommand ========="
  eval $finalcommand
done